services:
  - name: planning-poker-web
    type: web
    env: docker
    dockerContext: ./web
    dockerfilePath: ./web/Dockerfile
    plan: free

  - name: planning-poker-server
    type: web
    env: docker
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    plan: free
